- apt:
    pkg: "{{ item }}"
  sudo: True
  with_items:
    - git
    - libapache2-mod-php5
    - php5-ldap
    - php5-mcrypt
    - php5-mysql
    - php5-curl
    - php5-gmp
    - php-crypt-blowfish
    - libmcrypt4
    - subversion
