---
- apt:
    update_cache: yes
    cache_valid_time: 86400
  when: ansible_pkg_mgr == 'apt'

- include: apt.yml
  when: ansible_pkg_mgr == 'apt'

- include: yum.yml
  when: ansible_pkg_mgr == 'yum'

- name: clone github repo
  git:
    repo: "{{ simplesamlphp_repo }}"
    dest: "{{ simplesamlphp_dir }}"
    version: "{{ simplesamlphp_branch }}"

- command: cp -r config-templates config
  args:
    chdir: "{{ simplesamlphp_dir }}"
    creates: "{{ simplesamlphp_dir }}/config"

- command: cp -r metadata-templates metadata
  args:
    chdir: "{{ simplesamlphp_dir }}"
    creates: "{{ simplesamlphp_dir }}/metadata"

- template:
    src: simplesamlphp.conf
    dest: /etc/apache2/sites-available/simplesamlphp.conf
    backup: true
  when: ansible_os_family == 'Debian'

- template:
    src: simplesamlphp.conf
    dest: /etc/httpd/conf.d/simplesamlphp.conf
    backup: true
  when: ansible_os_family == 'RedHat'
  notify: restart apache

- lineinfile:
    backup: yes
    dest: "{{ '/etc/httpd/conf/httpd.conf' if ansible_os_family == 'RedHat' else '/etc/apache2/ports.conf' }}"
    insertafter: EOF
    line: "Listen {{ item }}"
  with_items:
    - 0.0.0.0:80
    - 0.0.0.0:443
  notify: restart apache

- stat:
    path: /etc/httpd/conf.d/welcome.conf
  when: ansible_os_family == 'RedHat'
  register: welcome

- replace:
    dest: /etc/httpd/conf.d/welcome.conf
    regexp: ^(?!#)(.*)$
    replace: '#\1'
  when: welcome.stat.exists
  notify: restart apache

- template:
    src: saml20-idp-hosted.php
    dest: "{{ simplesamlphp_dir }}/metadata/saml20-idp-hosted.php"
    backup: true

- template:
    src: authsources.php
    dest: "{{ simplesamlphp_dir }}/config/authsources.php"
    backup: true

- command: php5enmod mcrypt
  when: ansible_os_family == 'Debian'
  notify: restart apache

- shell: curl -sS https://getcomposer.org/installer | php
  args:
    chdir: "{{ simplesamlphp_dir }}"
    creates: "{{ simplesamlphp_dir }}/composer.phar"

- command: php composer.phar install
  args:
    chdir: "{{ simplesamlphp_dir }}"
    creates: "{{ simplesamlphp_dir }}/vendor"

- command: a2ensite simplesamlphp.conf
  when: ansible_os_family == 'Debian'
  notify: restart apache

- command: a2dissite 000-default.conf
  when: ansible_os_family == 'Debian'
  notify: restart apache

- command: a2enmod ssl
  when: ansible_os_family == 'Debian'
  notify: restart apache

# Generation of secret salt for the installation

- shell: grep -q Ansible_generated_salt "{{ simplesamlphp_dir }}"/config/config.php
  register: salt_found
  ignore_errors: True

- shell: tr -c -d '0123456789abcdefghijklmnopqrstuvwxyz' </dev/urandom | dd bs=32 count=1 2>/dev/null
  register: salt
  when: salt_found|failed

- lineinfile:
    dest:  "{{ simplesamlphp_dir }}/config/config.php"
    regexp: "secretsalt.*=>"
    line: "//Ansible_generated_salt\n  'secretsalt' => '{{salt.stdout}}',"
  when: salt_found|failed

- lineinfile:
    dest:  "{{ simplesamlphp_dir }}/config/config.php"
    regexp: "baseurlpath.*=>"
    line: "  'baseurlpath' => '{{ simplesamlphp_suburi }}/',"
    backup: yes
  notify: restart apache

- lineinfile:
    dest:  "{{ simplesamlphp_dir }}/config/config.php"
    regexp: "auth.adminpassword.*=>"
    line: "  'auth.adminpassword' => '{{ simplesamlphp_admin_password }}',"
    backup: yes
  notify: restart apache

- lineinfile:
    dest:  "{{ simplesamlphp_dir }}/config/config.php"
    regexp: "certdir.*=>"
    line: "  'certdir' => '{{ simplesamlphp_cert_dir }}',"
    backup: yes
  notify: restart apache

- lineinfile:
    dest:  "{{ simplesamlphp_dir }}/config/config.php"
    regexp: "enable.saml20-idp.*=>"
    line: "  'enable.saml20-idp' => true,"
    backup: yes
  notify: restart apache

- file:
    recurse: yes
    group: www-data
    owner: www-data
    path:  "{{ simplesamlphp_dir }}"
  when: ansible_os_family == 'Debian'

- file:
    recurse: yes
    group: apache
    owner: apache
    setype: httpd_sys_rw_content_t
    path:  "{{ simplesamlphp_dir }}"
  when: ansible_os_family == 'RedHat'

- debug:
    msg: "visit https://{{ ansible_fqdn }}/{{ simplesamlphp_suburi }}"
