- yum:
    name: "{{ item }}"
  sudo: True
  with_items:
    - git
    - httpd
    - mod_ssl
    - php
    - php-xml
    - php-ldap
    - php-mcrypt
    - php-mysql
    - php-curl
    - php-gmp
    - subversion
